events {}

http {
    upstream inference_api {
        server inference-api:8000;
    }

    upstream monitoring_api {
        server monitoring-service:8000;
    }

    server {
        listen 80;

        location /predict {
            proxy_pass http://inference_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /monitoring/ {
            rewrite ^/monitoring/(.*)$ /$1 break;
            proxy_pass http://monitoring_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
